--- 
- name: install and configure httpd
  hosts: all
  become: true
  tasks:
  - name: Installing httpd
    yum:
     name: httpd
     state: latest
  - name: start and enable service 
    service: 
      name: httpd
      state: started
      enabled: yes
...


